import { api, login, check, group, summary, uid } from "./testlib.mjs";
const tag = uid();
const { token: T } = await login("central", (process.env.VF_BOSS_P ?? "vfletch-dev"));
let r;
group("知识库回收站：归档(一级) → 恢复 / 彻底删除(二级)");
r = await api("POST", "/api/kb", { token: T, body: { title: `回收站测试 ${tag}`, content: "内容", tags: [] } });
const id = r.data.id;
check("发布文档", r.status === 200 && r.data.status === "active");
r = await api("POST", "/api/kb/purge", { token: T, body: { id } });
check("未归档直接彻底删除 → 400", r.status === 400, JSON.stringify(r.data));
r = await api("DELETE", `/api/kb/${id}`, { token: T });
check("归档", r.status === 200);
r = await api("GET", "/api/kb/archive", { token: T });
check("回收站可见", r.status === 200 && r.data.docs.some((d) => d.id === id));
r = await api("GET", "/api/kb", { token: T });
check("归档后列表不可见", !r.data.docs.some((d) => d.id === id));
r = await api("POST", "/api/mcp/call", { token: T, body: { name: "kb__kb_search", arguments: { query: `回收站测试 ${tag}` } } });
check("归档后 AI 检索不到", r.status === 200 && !r.data.text.includes(id));
r = await api("POST", "/api/kb/restore", { token: T, body: { id } });
check("恢复", r.status === 200);
r = await api("GET", "/api/kb", { token: T });
check("恢复后列表可见", r.data.docs.some((d) => d.id === id && d.status === "active"));
r = await api("DELETE", `/api/kb/${id}`, { token: T });
r = await api("POST", "/api/kb/purge", { token: T, body: { id } });
check("归档后彻底删除", r.status === 200 && r.data.removed === 1, JSON.stringify(r.data));
r = await api("GET", "/api/kb/archive", { token: T });
check("彻底删除后回收站不可见", !r.data.docs.some((d) => d.id === id));
r = await api("POST", "/api/kb/restore", { token: T, body: { id } });
check("恢复不存在文档 404", r.status === 404);
r = await api("POST", "/api/kb/purge", { token: T, body: { id: "nope" } });
check("彻底删除不存在文档 404", r.status === 404);
group("在线状态接口");
r = await api("GET", "/api/admin/online", { token: T });
check("/api/admin/online 正常且主控在线", r.status === 200 && r.data.online.some((u) => u.username === "central"), JSON.stringify(r.data).slice(0, 200));
process.exit(summary() ? 0 : 1);
